spring:
  datasource:
    url: jdbc:h2:mem:adm_picpay_test;MODE=MYSQL;DATABASE_TO_LOWER=TRUE # É possível persistir em um arquivo alterando "mem:adm_videos_test" para "file:./.h2/dev"
    driver-class-name: org.h2.Driver
    username: root
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2