mysql:
  username: ${DATABASE_MYSQL_USERNAME:root}
  password: ${DATABASE_MYSQL_PASSWORD:Tulipa123}
  schema: adm_videos
  url: ${DATABASE_MYSQL_URL:localhost:33006}

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none